Repository tracked-tools/ember-async-data, pull requests merged in 2022-10, with the labels that each got.

#358 Bump release-it and update plugins
  package.json
  yarn.lock
Labels: dependencies

#301 Require Node 14, support Node 16 and 18
  .github/workflows/CI.yml
  README.md
  package.json
Labels: enhancement, breaking

#300 Set minimum Ember version to 3.28
  .github/workflows/CI.yml
  README.md
  config/ember-try.js
  package.json
Labels: breaking

#359 update hbs import from ember-cli-htmlbars
  README.md
  tests/integration/helpers/load-test.ts
Labels: documentation

#366 Bump @typescript-eslint/* packages
  package.json
  yarn.lock
Labels: dependencies
