Repository tracked-tools/ember-async-data, pull requests merged in 2023-03, with the labels that each got.

#575 Add hard error and deprecations for 1.0
  ember-async-data/src/tracked-async-data.ts
Labels: enhancement, breaking

#527 Drop TypeScript support for <= 4.7
  .github/workflows/ci.yml
  README.md
Labels: breaking

#578 Bugfix: drop `context` and stop caching `TrackedAsyncData`
  README.md
  ember-async-data/src/helpers/load.ts
  ember-async-data/src/tracked-async-data.ts
  ember-async-data/type-tests/load-test.ts
  ember-async-data/type-tests/tracked-async-data-test.ts
  test-app/tests/unit/helpers/load-test.ts
  test-app/tests/unit/tracked-async-data-test.ts
Labels: bug

#581 Backport context bug fix to 0.5.x
  .github/workflows/CI.yml
  README.md
  addon/helpers/load.ts
  addon/tracked-async-data.ts
  config/ember-try-typescript.js
  config/ember-try.js
  tests/unit/helpers/load-test.ts
  tests/unit/tracked-async-data-test.ts
  type-tests/load-test.ts
Labels: bug

#582 Backport context bug fix to 0.6.x
  .github/workflows/CI.yml
  README.md
  addon/helpers/load.ts
  addon/tracked-async-data.ts
  config/ember-try-typescript.js
  config/ember-try.js
  tests/unit/helpers/load-test.ts
  tests/unit/tracked-async-data-test.ts
  type-tests/load-test.ts
  type-tests/tracked-async-data-test.ts
Labels: bug

#583 Backport context bug fix to 0.7.x
  README.md
  ember-async-data/src/helpers/load.ts
  ember-async-data/src/tracked-async-data.ts
  ember-async-data/type-tests/load-test.ts
  ember-async-data/type-tests/tracked-async-data-test.ts
  test-app/tests/unit/helpers/load-test.ts
  test-app/tests/unit/tracked-async-data-test.ts
Labels: bug
